remote_theme: just-the-docs/just-the-docs

# Core Site Settings
title: Verifiable Credential Papers
description: A repository for Verifiable Credential research and documentation.

# Enable Mermaid Diagram Rendering. Version set on 2026-07-22
mermaid:
  version: "10.9.1"

# Enable MathJax Math Rendering
math:
  enabled: true

kramdown:
  math_engine: mathjax
  # 🔌 Forces Jekyll to recognize single dollar signs as inline math
  input: GFM 

# Just the Docs specific configurations
nav_sort: case_insensitive # Automatically sorts pages by title

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  tip:
    title: Pro Tip
    color: green